/**
 * Registry of every static map shipped with the game, keyed by its id.
 *
 * Add extracted maps here (see `scripts/extract-freeciv-map.mjs`) to make them
 * selectable; hand-tuned maps are generated by their own script (e.g.
 * `scripts/generate-naval-map.mjs`).
 */
import earth180x90 from './earth-180x90.json';
import navalArchipelago from './naval-archipelago-96x60.json';
import { validateStaticMap, type StaticMapDefinition } from './types';

export * from './types';

/** All static maps, keyed by their id. */
export const STATIC_MAPS: Record<string, StaticMapDefinition> = {
  'earth-180x90': earth180x90 as StaticMapDefinition,
  'naval-archipelago-96x60': navalArchipelago as StaticMapDefinition,
};

/** Id of the map used for the in-game world map ("Earth" map type). */
export const WORLD_MAP_ID = 'earth-180x90';

/** The static world map (undefined when the data file is missing). */
export const WORLD_MAP: StaticMapDefinition | undefined = STATIC_MAPS[WORLD_MAP_ID];

/**
 * Which static map backs a map type, if any. Scenarios that ship a hand-tuned
 * world (the Earth map, the naval archipelago) use this instead of the
 * procedural generator, so their layout — and their start positions — are the
 * same on every machine and every run.
 */
export const STATIC_MAP_FOR_MAP_TYPE: Readonly<Record<string, string>> = {
  EARTH: WORLD_MAP_ID,
  AI_VS_AI_NAVAL: 'naval-archipelago-96x60',
};

/** The static map a map type uses, or undefined when it is generated. */
export function staticMapForMapType(mapType: string | undefined): StaticMapDefinition | undefined {
  const id = mapType ? STATIC_MAP_FOR_MAP_TYPE[mapType] : undefined;
  return id ? STATIC_MAPS[id] : undefined;
}

// A malformed data file would otherwise show up as a broken world much later
// (or as an unplayable map), so shout about it at load time instead.
for (const [id, def] of Object.entries(STATIC_MAPS)) {
  const errors = validateStaticMap(def);
  if (errors.length > 0) {
    console.error(`[maps] static map "${id}" is invalid: ${errors.join('; ')}`);
  }
}
