/**
 * City-related calculation utilities
 */

import { BUILDING_TYPES } from '@/data/BuildingConstants';
import type { City, Civilization } from '../../types/game';

export const CityUtils = {
    /**
     * Calculate corruption for a city based on distance from capital and government type
     * @param city - City object
     * @param currentPlayer - Current player object
     * @param totalTrade - Total trade generated by the city
     * @returns Corruption amount
     */
    calculateCorruption: (city: City, currentPlayer: Civilization, totalTrade: number): number => {
        if (!currentPlayer || !city) return 0;

        // Find the capital city
        const capital = currentPlayer.capital;
        if (!capital) return 0;

        // If this is the capital, no corruption
        if (city.id === capital.id) return 0;

        // Calculate distance from capital
        const distance = Math.sqrt(
            Math.pow(city.col - capital.col, 2) +
            Math.pow(city.row - capital.row, 2)
        );

        // Base corruption rate depends on government type
        // For now, assume despotism (high corruption)
        const baseCorruptionRate = 0.3; // 30% base corruption for despotism

        // Distance increases corruption
        const distanceMultiplier = Math.min(distance / 10, 2); // Max 2x at distance 10+
        // Apply building reductions (Courthouse reduces corruption)
        let finalCorruptionRate = baseCorruptionRate * distanceMultiplier;
        if (city.buildings?.includes('courthouse')) {
            finalCorruptionRate *= 0.5; // Courthouse reduces corruption by 50%
        }

        return Math.floor(totalTrade * finalCorruptionRate);
    },

    /**
     * Calculate comprehensive city resource data
     * @param city - City object
     * @param currentPlayer - Current player object
     * @returns Object containing all city resource calculations
     */
    calculateCityResources: (city: City, currentPlayer: Civilization) => {
        // Calculate food surplus/shortfall
        const population = city.population ?? 1;
        const foodNeeded = population * 2;
        const foodProduced = city.yields?.food ?? city.food ?? 0;
        const foodSurplus = foodProduced - foodNeeded;

        // Calculate production surplus/shortfall (simplified - assuming no unit maintenance for now)
        const productionProduced = city.yields?.production ?? city.production ?? 0;
        const productionSurplus = productionProduced; // Simplified - no maintenance cost calculation yet

        // Calculate trade and its distribution: tile trade plus per-turn income
        // from permanent trade routes (established by delivered Caravans).
        const routeTrade = (city.tradeRoutes ?? []).reduce(
          (total: number, r) => total + (r.trade ?? 0),
          0,
        );
        const totalTrade = (city.yields?.trade ?? 0) + routeTrade;

        // Use the civ's actual Tax/Science/Luxury rates (fallback 50/50/0).
        const luxuryRate = currentPlayer?.luxuryRate ?? 0;      // percentage
        const taxRate = currentPlayer?.taxRate ?? 50;           // percentage
        const scienceRate = currentPlayer?.scienceRate ?? 50;   // percentage

        // Calculate corruption based on distance from capital and government
        const corruption = CityUtils.calculateCorruption(city, currentPlayer, totalTrade);
        const tradeAfterCorruption = totalTrade - corruption;

        // Distribute trade after corruption
        const actualLuxuries = Math.floor(tradeAfterCorruption * (luxuryRate / 100));
        const actualTaxes = Math.floor(tradeAfterCorruption * (taxRate / 100));
        const actualScience = Math.floor(tradeAfterCorruption * (scienceRate / 100));

        // Growth calculations
        const growthThreshold = (population + 1) * 10;
        const foodStorage = city.foodStored ?? 0;
        const hasGranary = city.buildings?.includes?.(BUILDING_TYPES.GRANARY) ?? false;
        const granaryLine = hasGranary ? Math.floor(growthThreshold / 2) : 0;
        const turnsUntilGrowth = foodSurplus > 0 ? Math.ceil((growthThreshold - foodStorage) / foodSurplus) : -1;
        const turnsUntilStarvation = foodSurplus < 0 ? Math.ceil(foodStorage / Math.abs(foodSurplus)) : -1;

        return {
            food: {
                produced: foodProduced,
                needed: foodNeeded,
                surplus: foodSurplus,
                storage: foodStorage,
                growthThreshold,
                granaryLine,
                hasGranary,
                turnsUntilGrowth,
                turnsUntilStarvation,
                population: city.population ?? 1
            },
            production: {
                produced: productionProduced,
                surplus: productionSurplus
            },
            trade: {
                total: totalTrade,
                afterCorruption: tradeAfterCorruption,
                corruption: corruption,
                routeTrade: routeTrade
            },
            luxuries: {
                amount: actualLuxuries,
                rate: luxuryRate
            },
            taxes: {
                amount: actualTaxes,
                rate: taxRate
            },
            science: {
                amount: actualScience,
                rate: scienceRate
            }
        };
    }
};